[2025-09-28 08:38:43] ErrorException: http_response_code(): Cannot set response code - headers already sent (output started at /var/www/html/api/helpers/globalHelpers.php:32) in /var/www/html/api/helpers/globalHelpers.php:98
Request: GET /api/test
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36
IP: 172.18.0.1
Stack trace:
#0 [internal function]: App\Core\ExceptionHandler::handleError(2, 'http_response_c...', '/var/www/html/a...', 98)
#1 /var/www/html/api/helpers/globalHelpers.php(98): http_response_code(200)
#2 /var/www/html/api/controllers/BaseController.php(24): sendJsonResponse(200, 'success', 'Test complete', 'SELECT * FROM a...', NULL)
#3 /var/www/html/api/controllers/AuthController.php(86): App\Controllers\BaseController->sendSuccess('Test complete', 'SELECT * FROM a...')
#4 [internal function]: App\Controllers\AuthController->test2()
#5 /var/www/html/api/Router.php(102): call_user_func_array(Array, Array)
#6 /var/www/html/api/index.php(91): App\Router->dispatch()
#7 {main}
---
[2025-09-28 08:38:43] ErrorException: Uncaught ErrorException: http_response_code(): Cannot set response code - headers already sent (output started at /var/www/html/api/helpers/globalHelpers.php:32) in /var/www/html/api/helpers/globalHelpers.php:98
Stack trace:
#0 [internal function]: App\Core\ExceptionHandler::handleError(2, 'http_response_c...', '/var/www/html/a...', 98)
#1 /var/www/html/api/helpers/globalHelpers.php(98): http_response_code(500)
#2 /var/www/html/api/core/ExceptionHandler.php(95): sendJsonResponse(500, 'error', 'http_response_c...', Array)
#3 [internal function]: App\Core\ExceptionHandler::handle(Object(ErrorException))
#4 {main}
  thrown in /var/www/html/api/helpers/globalHelpers.php:98
Request: GET /api/test
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36
IP: 172.18.0.1
Stack trace:
#0 [internal function]: App\Core\ExceptionHandler::handleShutdown()
#1 {main}
---
[2025-09-28 08:38:57] ErrorException: http_response_code(): Cannot set response code - headers already sent (output started at /var/www/html/api/helpers/globalHelpers.php:32) in /var/www/html/api/helpers/globalHelpers.php:98
Request: GET /api/test
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36
IP: 172.18.0.1
Stack trace:
#0 [internal function]: App\Core\ExceptionHandler::handleError(2, 'http_response_c...', '/var/www/html/a...', 98)
#1 /var/www/html/api/helpers/globalHelpers.php(98): http_response_code(200)
#2 /var/www/html/api/controllers/BaseController.php(24): sendJsonResponse(200, 'success', 'Test complete', 'SELECT * FROM a...', NULL)
#3 /var/www/html/api/controllers/AuthController.php(86): App\Controllers\BaseController->sendSuccess('Test complete', 'SELECT * FROM a...')
#4 [internal function]: App\Controllers\AuthController->test2()
#5 /var/www/html/api/Router.php(102): call_user_func_array(Array, Array)
#6 /var/www/html/api/index.php(91): App\Router->dispatch()
#7 {main}
---
[2025-09-28 08:38:57] ErrorException: Uncaught ErrorException: http_response_code(): Cannot set response code - headers already sent (output started at /var/www/html/api/helpers/globalHelpers.php:32) in /var/www/html/api/helpers/globalHelpers.php:98
Stack trace:
#0 [internal function]: App\Core\ExceptionHandler::handleError(2, 'http_response_c...', '/var/www/html/a...', 98)
#1 /var/www/html/api/helpers/globalHelpers.php(98): http_response_code(500)
#2 /var/www/html/api/core/ExceptionHandler.php(95): sendJsonResponse(500, 'error', 'http_response_c...', Array)
#3 [internal function]: App\Core\ExceptionHandler::handle(Object(ErrorException))
#4 {main}
  thrown in /var/www/html/api/helpers/globalHelpers.php:98
Request: GET /api/test
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36
IP: 172.18.0.1
Stack trace:
#0 [internal function]: App\Core\ExceptionHandler::handleShutdown()
#1 {main}
---
[2025-09-28 08:40:31] ErrorException: http_response_code(): Cannot set response code - headers already sent (output started at /var/www/html/api/helpers/globalHelpers.php:32) in /var/www/html/api/helpers/globalHelpers.php:98
Request: GET /api/test
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36
IP: 172.18.0.1
Stack trace:
#0 [internal function]: App\Core\ExceptionHandler::handleError(2, 'http_response_c...', '/var/www/html/a...', 98)
#1 /var/www/html/api/helpers/globalHelpers.php(98): http_response_code(200)
#2 /var/www/html/api/controllers/BaseController.php(24): sendJsonResponse(200, 'success', 'Test complete', 'SELECT * FROM a...', NULL)
#3 /var/www/html/api/controllers/AuthController.php(86): App\Controllers\BaseController->sendSuccess('Test complete', 'SELECT * FROM a...')
#4 [internal function]: App\Controllers\AuthController->test2()
#5 /var/www/html/api/Router.php(102): call_user_func_array(Array, Array)
#6 /var/www/html/api/index.php(91): App\Router->dispatch()
#7 {main}
---
[2025-09-28 08:40:31] ErrorException: Uncaught ErrorException: http_response_code(): Cannot set response code - headers already sent (output started at /var/www/html/api/helpers/globalHelpers.php:32) in /var/www/html/api/helpers/globalHelpers.php:98
Stack trace:
#0 [internal function]: App\Core\ExceptionHandler::handleError(2, 'http_response_c...', '/var/www/html/a...', 98)
#1 /var/www/html/api/helpers/globalHelpers.php(98): http_response_code(500)
#2 /var/www/html/api/core/ExceptionHandler.php(95): sendJsonResponse(500, 'error', 'http_response_c...', Array)
#3 [internal function]: App\Core\ExceptionHandler::handle(Object(ErrorException))
#4 {main}
  thrown in /var/www/html/api/helpers/globalHelpers.php:98
Request: GET /api/test
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36
IP: 172.18.0.1
Stack trace:
#0 [internal function]: App\Core\ExceptionHandler::handleShutdown()
#1 {main}
---
[2025-09-28 08:45:41] Error: Call to undefined function App\Controllers\testing2() in /var/www/html/api/controllers/AuthController.php:84
Request: GET /api/test
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36
IP: 172.18.0.1
Stack trace:
#0 [internal function]: App\Controllers\AuthController->test2()
#1 /var/www/html/api/Router.php(102): call_user_func_array(Array, Array)
#2 /var/www/html/api/index.php(91): App\Router->dispatch()
#3 {main}
---
[2025-09-28 08:45:41] ErrorException: Uncaught ErrorException: http_response_code(): Cannot set response code - headers already sent (output started at /var/www/html/api/helpers/globalHelpers.php:32) in /var/www/html/api/helpers/globalHelpers.php:98
Stack trace:
#0 [internal function]: App\Core\ExceptionHandler::handleError(2, 'http_response_c...', '/var/www/html/a...', 98)
#1 /var/www/html/api/helpers/globalHelpers.php(98): http_response_code(500)
#2 /var/www/html/api/core/ExceptionHandler.php(95): sendJsonResponse(500, 'error', 'Call to undefin...', Array)
#3 [internal function]: App\Core\ExceptionHandler::handle(Object(Error))
#4 {main}
  thrown in /var/www/html/api/helpers/globalHelpers.php:98
Request: GET /api/test
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36
IP: 172.18.0.1
Stack trace:
#0 [internal function]: App\Core\ExceptionHandler::handleShutdown()
#1 {main}
---
[2025-09-28 08:45:54] Error: Call to undefined function App\Controllers\testing2() in /var/www/html/api/controllers/AuthController.php:84
Request: GET /api/test
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36
IP: 172.18.0.1
Stack trace:
#0 [internal function]: App\Controllers\AuthController->test2()
#1 /var/www/html/api/Router.php(102): call_user_func_array(Array, Array)
#2 /var/www/html/api/index.php(91): App\Router->dispatch()
#3 {main}
---
[2025-09-28 08:46:10] Error: Call to undefined function App\Controllers\testing2() in /var/www/html/api/controllers/AuthController.php:84
Request: GET /api/test
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36
IP: 172.18.0.1
Stack trace:
#0 [internal function]: App\Controllers\AuthController->test2()
#1 /var/www/html/api/Router.php(102): call_user_func_array(Array, Array)
#2 /var/www/html/api/index.php(91): App\Router->dispatch()
#3 {main}
---
[2025-09-28 08:48:07] Error: Call to undefined function App\Controllers\testing2() in /var/www/html/api/controllers/AuthController.php:84
Request: GET /api/test
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36
IP: 172.18.0.1
Stack trace:
#0 [internal function]: App\Controllers\AuthController->test2()
#1 /var/www/html/api/Router.php(102): call_user_func_array(Array, Array)
#2 /var/www/html/api/index.php(91): App\Router->dispatch()
#3 {main}
---
[2025-09-28 08:48:15] Error: Call to undefined function App\Controllers\testing2() in /var/www/html/api/controllers/AuthController.php:84
Request: GET /api/test
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36
IP: 172.18.0.1
Stack trace:
#0 [internal function]: App\Controllers\AuthController->test2()
#1 /var/www/html/api/Router.php(102): call_user_func_array(Array, Array)
#2 /var/www/html/api/index.php(91): App\Router->dispatch()
#3 {main}
---
